### probar el endpoint para conseguir todos los productos
GET http://localhost:3000/product/all

### probar el endpoint para conseguir un producto por id
GET http://localhost:3000/product/6eab4ded-de40-4483-b053-db590737286f

### probar el endponit para crear un producto
POST http://localhost:3000/product/create
Content-Type: application/json

{
    "name": "Zapatos Old School", 
    "brand": "Vans",
    "price": 70.99, 
    "description": "Zapatos de lona con suela de goma.", 
    "category": "Moda", 
    "link": "http://link.jpg", 
    "rate": 4.5, 
    "stock": 10
}

### probar el endpoint para actualizar un producto
PATCH http://localhost:3000/product/43517a87-a546-42d7-b0f6-c208aa7bb6da
Content-Type: application/json

{
    "name": "Zapatos"
}

### probar borrar un producto
DELETE http://localhost:3000/product/91e97673-329d-11f0-a1c6-20c19b38cd45