### Probar el endpoint para conseguir los usuarios.
GET http://localhost:3000/user/6a92d24b-5a73-4f94-9563-c667d76040c2

### Probar la creación de usuarios.
POST http://localhost:3000/user
Content-Type: application/json

{
    "username": "Astaroth_25",
    "fname": "Angelo", 
    "lname": "Franco", 
    "email": "angelo0984841543@gmail.com", 
    "role": "Buyer", 
    "password": "12345"
}

### Probar la actualizacion de usuarios.
PATCH http://localhost:3000/user/c92acb75-315f-48d2-bf3a-1ef2dad67cfa
Content-Type: application/json

{
    "username": "Astaroth",
    "fname": "Angelo Octavio"
}

### Probar el borrado de usuarios.
DELETE http://localhost:3000/user/6a92d24b-5a73-4f94-9563-c667d76040c2

### Probar el login
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "username": "Astaroth",
    "password": "12345"
}

### Probar el logout
POST http://localhost:3000/user/logout
Content-Type: application/json

{
}